config/routes.rb
Rails.application.routes.draw do
  get "support_requests/index"

  get "admin" => "admin#index"
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  # get "sessions/new"
  # get "sessions/create"
  # get "sessions/destroy"

  resources :support_requests, only: %i[ index update]
  resources :users

  resources :products do
    get :who_bought, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end
end

app/views/layouts/_cart.html.erb
<% if cart and not cart.line_items.empty? %>
  <div id="cart" class="bg-white rounded p-2">
    <%= render cart %>
  </div>
  <% else %>
    <div id="cart"></div>
<% end %>

app/views/layouts/_notice.html.erb
<% if notice.present? %>
  <p id="notice" class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block">
    <%= notice %>
  </p>
  <% else %>
  <div id="notice"></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Depot" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%#= stylesheet_link_tag "tailwind/application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="bg-green-700">
      <div class="flex items-center justify-between px-4 py-2">
        <%= image_tag('teslasign.jpg', class: 'object-content w-40 h-28 shadow mr-6 rounded-lg', alt: 'The Pragmatic Bookshelf') %>

        <aside data-controller="locale">
          <%= form_tag store_index_path, class: 'locale' do %>
            <%= select_tag 'set_locale',
                           options_for_select(LANGUAGE, I18n.locale.to_s),
                           onchange: "this.form.submit();"
            %>
            <%= submit_tag 'submit', data: {'locale-target' => 'submit'} %>
          <% end %>
        </aside>
      </div>

      <h1> <%= @page_title %> </h1>
    </header>

    <section class="flex">
      <nav class="bg-green-900 p-6">
        <%# if @cart and not @cart.line_items.empty? %>
<!--          <div id="cart" class="bg-white rounded p-2">-->
            <%#= render @cart %>
<!--          </div>-->
        <%# end %>

        <%= render partial: 'layouts/cart', locals: {cart: @cart}%>

        <ul class="text-gray-300 leading-8">
          <li> <a href="/"> <%= t('.home') %> </a> </li>
          <li> <a href="/questions"> <%= t('.questions') %> </a> </li>
          <li> <a href="/news"> <%= t('.news') %> </a> </li>
          <li> <a href="/contact"> <%= t('.contact') %> </a> </li>
        </ul>

        <% if session[:user_id] %>
          <hr class="my-2">
          <ul class="text-gray-300 leading-8">
            <li><%= link_to 'Orders', orders_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= button_to 'Logout', logout_path, method: :delete %></li>
          </ul>
        <% end %>

      </nav>

      <main class="container mx-auto mt-4 px-5 flex">
        <%= yield %>
      </main>
    </section>
  </body>
</html>